apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: ooh-test
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: ooh-test
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ooh-cache
  namespace: ooh-test
  labels:
    app.kubernetes.io/name: ooh-test
    app.kubernetes.io/part-of: ooh-test
    app.kubernetes.io/component: cache
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
